# Generated by Django 3.1.1 on 2020-10-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ChemicalComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=19)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chemical_compositions', to='metallics_optimization.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('inventory', models.DecimalField(decimal_places=2, max_digits=19)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('chemical_composition', models.ManyToManyField(related_name='commodities', to='metallics_optimization.ChemicalComposition')),
            ],
        ),
    ]
