# Generated by Django 3.1.1 on 2020-10-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metallics_optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chemical',
            options={'verbose_name': 'chemical', 'verbose_name_plural': 'chemicals'},
        ),
        migrations.AlterModelOptions(
            name='chemicalcomposition',
            options={'verbose_name': 'chemical_composition', 'verbose_name_plural': 'chemical_compositions'},
        ),
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name': 'commodity', 'verbose_name_plural': 'commidities'},
        ),
    ]
